quarkus.oidc.provider=google
quarkus.oidc.client-id=538726785952-jqvlb8h7bo2vp89go0ks5vnhimgd10a9.apps.googleusercontent.com
quarkus.oidc.credentials.secret=${QUARKUS_OIDC_CREDENTIALS_SECRET}
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.redirect-path=/callback
quarkus.oidc.authentication.scopes=openid,email,profile
