# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25 (GraalVM)
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'

      - name: Build with Maven
        env:
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: mvn -B clean install

      - name: Add Coverage PR Comment
        uses: Madrapps/jacoco-report@v1.6.1
        if: github.event_name == 'pull_request'
        with:
          paths: ${{ github.workspace }}/target/jacoco-report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: 'Code Coverage Report'

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/jacoco-report/jacoco.csv
          badges-directory: .github/badges

      - name: Commit the badge (if it changed)
        # This ensures the bot only tries to push when you merge or push to main directly
        if: github.event_name == 'push'
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add .github/badges/jacoco.svg
            git commit -m "chore: autogenerated JaCoCo coverage badge"
            # Explicitly route the push back to the correct branch
            git push origin HEAD:${{ github.ref_name }}
          fi